<?php /*?><?php $_cartQty = $this->getSummaryCount() ?>

<div class="block block-mini-cart">    
	<strong><?php echo $this->__('Shopping Cart')?>:</strong>
	<?php if ($_cartQty>0): ?>
       	<?php echo $this->__('now in your cart ')?>
      
       	<?php if ($_cartQty==1): ?>
           	<?php echo $this->__('<a href="%s">1 item</a>', $this->getUrl('checkout/cart'), $_cartQty) ?>      
    	<?php else: ?>
       		<?php echo $this->__('<a href="%s">%s items</a>', $this->getUrl('checkout/cart'), $_cartQty) ?>      
    	<?php endif ?>
  	<?php else: ?>
    	<?php echo $this->__('your cart is empty.')?>        
    <?php endif ?>
</div><?php */?> 


<?php /*?><a class="summary" href="#"><strong>2</strong> items in winkelmand  <span class="total">€ 8.50</span></a><?php */?>

<?php $_cartQty = $this->getSummaryCount() ?>
<?php $total = $this->helper('checkout/cart')->getQuote()->getGrandTotal(); //get total price ?>
<?php //echo $this->__($this->helper('core')->formatPrice($total, false)); ?>

<div class="block block-mini-cart">    
	<?php /*?><strong><?php echo $this->__('Shopping Cart')?>:</strong><?php */?>
	<?php if ($_cartQty>0): ?>
       	<?php //echo $this->__('now in your cart ')?>
      
       	<?php if ($_cartQty==1): ?>
           	<?php echo $this->__('<a class="summary" href="%s"><strong>1</strong> item in winkelmand <span class="total">'.$this->__($this->helper('core')->formatPrice($total, false)).'</span></a>', $this->getUrl('checkout/cart'), $_cartQty) ?>      
    	<?php else: ?>
       		<?php echo $this->__('<a class="summary" href="%s"><strong>%s</strong> items in winkelmand <span class="total">'.$this->__($this->helper('core')->formatPrice($total, false)).'</span></a>', $this->getUrl('checkout/cart'), $_cartQty) ?>      
    	<?php endif ?>        
                        
  	<?php else: ?>
    	<?php echo $this->__('<a class="summary" href="%s">No item in winkelmand <span class="total">€ 0.00</span></a>', $this->getUrl('checkout/cart'), $_cartQty)?>        
    <?php endif ?>
</div>